<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'شمع رقم 1',
                'model' => 'تاج',
                'price_cost' => 1000,
                'quantity' => 10,
                'price' => 3000,
                'currency' => 'IQD',
                'barcode' => '1',
                'is_active' => true,
                'is_featured' => true,
                'is_best_selling' => true,
                'sales_count' => 25,
                'image' => 'products/default_product.png',
            ],
            [
                'name' => 'شمع رقم 2',
                'price_cost' => 1000,
                'quantity' => 30,
                'price' => 3000,
                'currency' => 'IQD',
                'barcode' => '2',
                'is_active' => true,
                'is_featured' => false,
                'is_best_selling' => true,
                'sales_count' => 20,
                'image' => 'products/default_product.png',
            ],
            [
                'name' => 'شمع رقم 3',
                'model' => 'تاج',
                'price_cost' => 1500,
                'quantity' => 15,
                'price' => 3500,
                'currency' => 'IQD',
                'barcode' => '3',
                'is_active' => true,
                'image' => 'products/default_product.png',
            ],
            [
                'name' => 'ثيم ماربو 6 قطع',
                'price_cost' => 5000,
                'quantity' => 4,
                'price' => 10000,
                'currency' => 'IQD',
                'barcode' => '5',
                'is_active' => true,
                'is_featured' => true,
                'is_best_selling' => false,
                'sales_count' => 8,
                'image' => 'products/default_product.png',
            ],
            [
                'name' => 'ثيم روبلكس',
                'price_cost' => 3500,
                'quantity' => 6,
                'price' => 8000,
                'currency' => 'IQD',
                'barcode' => '6',
                'is_active' => true,
                'image' => 'products/default_product.png',
            ],
            [
                'name' => 'ثيم هيلو كيتي',
                'price_cost' => 4000,
                'quantity' => 6,
                'price' => 15000,
                'currency' => 'IQD',
                'barcode' => '7',
                'is_active' => true,
                'image' => 'products/default_product.png',
            ],
            [
                'name' => 'بالون رقم1',
                'price_cost' => 1500,
                'quantity' => 6,
                'price' => 500,
                'currency' => 'IQD',
                'barcode' => '8',
                'is_active' => true,
                'image' => 'products/default_product.png',
            ],
            [
                'name' => 'بالون رقم2',
                'price_cost' => 2000,
                'quantity' => 10,
                'price' => 7500,
                'currency' => 'IQD',
                'barcode' => '9',
                'is_active' => true,
                'image' => 'products/default_product.png',
            ],
            [
                'name' => '1نشرة شخصيات',
                'price_cost' => 2000,
                'quantity' => 4,
                'price' => 5000,
                'currency' => 'IQD',
                'barcode' => '5201184954072',
                'is_active' => true,
                'image' => 'products/default_product.png',
            ],
            [
                'name' => 'نشرة شخصيات ايلسا',
                'model' => '2',
                'price_cost' => 2000,
                'quantity' => 3,
                'price' => 5000,
                'currency' => 'IQD',
                'barcode' => '5201184954041',
                'is_active' => true,
                'image' => 'products/default_product.png',
            ],
            [
                'name' => 'نشرة شخصيات اميرات',
                'model' => '3',
                'price_cost' => 2000,
                'quantity' => 2,
                'price' => 5000,
                'currency' => 'IQD',
                'barcode' => '5201184954010',
                'is_active' => true,
                'image' => 'products/default_product.png',
            ],
            [
                'name' => 'نشرة شخصيات بابترول',
                'model' => '4',
                'price_cost' => 2000,
                'quantity' => 1,
                'price' => 5000,
                'currency' => 'IQD',
                'barcode' => '5201184954065',
                'is_active' => true,
                'image' => 'products/default_product.png',
            ],
            [
                'name' => 'كيس شخصيات',
                'model' => 'مشكل',
                'price_cost' => 1000,
                'quantity' => 51,
                'price' => 3000,
                'currency' => 'IQD',
                'barcode' => '8682678902392',
                'is_active' => true,
                'image' => 'products/default_product.png',
            ],
            [
                'name' => 'نشرات هابي  بيرذدي 1',
                'price_cost' => 3000,
                'quantity' => 2,
                'price' => 5000,
                'currency' => 'IQD',
                'barcode' => '8762220190535',
                'is_active' => true,
                'image' => 'products/default_product.png',
            ],
            [
                'name' => 'نشرات هابي  بيرذدي 2',
                'price_cost' => 3000,
                'quantity' => 3,
                'price' => 5000,
                'currency' => 'IQD',
                'barcode' => '6972537466731',
                'is_active' => true,
                'image' => 'products/default_product.png',
            ],
            [
                'name' => 'نشرات هابي  بيرذدي 3',
                'price_cost' => 3000,
                'quantity' => 3,
                'price' => 5000,
                'currency' => 'IQD',
                'barcode' => '6860210778120',
                'is_active' => true,
                'image' => 'products/default_product.png',
            ],
            [
                'name' => 'صحن  اطفال',
                'price_cost' => 2000,
                'quantity' => 49,
                'price' => 2500,
                'currency' => 'IQD',
                'barcode' => '6281234500014',
                'is_active' => true,
                'image' => 'products/default_product.png',
            ],
            [
                'name' => 'بوكس بوشار',
                'price_cost' => 2000,
                'quantity' => 64,
                'price' => 3000,
                'currency' => 'IQD',
                'barcode' => '6281234500021',
                'is_active' => true,
                'image' => 'products/default_product.png',
            ],
            [
                'name' => 'بوكس كارتون',
                'price_cost' => 3000,
                'quantity' => 13,
                'price' => 5000,
                'currency' => 'IQD',
                'barcode' => '6281234500076',
                'is_active' => true,
                'image' => 'products/default_product.png',
            ],
            [
                'name' => 'صحن اطفال دبل عدد',
                'price_cost' => 3000,
                'quantity' => 4,
                'price' => 4000,
                'currency' => 'IQD',
                'barcode' => '6281234500045',
                'is_active' => true,
                'image' => 'products/default_product.png',
            ],
            [
                'name' => 'صحن اطفالحجم كبير',
                'price_cost' => 2000,
                'quantity' => 14,
                'price' => 3000,
                'currency' => 'IQD',
                'barcode' => '6281234500038',
                'is_active' => true,
                'image' => 'products/default_product.png',
            ],
            [
                'name' => 'كاسات اطفال حجم  صغير',
                'price_cost' => 1000,
                'quantity' => 4,
                'price' => 1500,
                'currency' => 'IQD',
                'barcode' => '6281234500052',
                'is_active' => true,
                'image' => 'products/default_product.png',
            ],
            [
                'name' => 'كلينكس اطفال',
                'price_cost' => 1000,
                'quantity' => 4,
                'price' => 1500,
                'currency' => 'IQD',
                'barcode' => '6281234500069',
                'is_active' => true,
                'image' => 'products/default_product.png',
            ],
            [
                'name' => 'نشرة ميكي ماوس',
                'price_cost' => 2000,
                'quantity' => 2,
                'price' => 2500,
                'currency' => 'IQD',
                'barcode' => '6424790795474',
                'is_active' => true,
                'image' => 'products/default_product.png',
            ],
            [
                'name' => 'نشرة هابي يوكيمون',
                'price_cost' => 2000,
                'quantity' => 3,
                'price' => 2500,
                'currency' => 'IQD',
                'barcode' => '5255223227856',
                'is_active' => true,
                'image' => 'products/default_product.png',
            ],
            [
                'name' => 'نشرة هابي باربي',
                'price_cost' => 2500,
                'quantity' => 2,
                'price' => 3000,
                'currency' => 'IQD',
                'barcode' => '6952392386030',
                'is_active' => true,
                'image' => 'products/default_product.png',
            ],
            [
                'name' => 'نشرة هابي ايلسا',
                'price_cost' => 2000,
                'quantity' => 2,
                'price' => 3000,
                'currency' => 'IQD',
                'barcode' => '7985414151230',
                'is_active' => true,
                'image' => 'products/default_product.png',
            ],
            [
                'name' => 'نشرة هابي دب العسل',
                'price_cost' => 2000,
                'quantity' => 1,
                'price' => 2500,
                'currency' => 'IQD',
                'barcode' => '5255223227825',
                'is_active' => true,
                'image' => 'products/default_product.png',
            ],
            [
                'name' => 'نشرة هابي سبايدرمان',
                'price_cost' => 2000,
                'quantity' => 1,
                'price' => 2500,
                'currency' => 'IQD',
                'barcode' => '6312305202206',
                'is_active' => true,
                'image' => 'products/default_product.png',
            ],
            [
                'name' => 'نشرة هابي  فيونكة',
                'price_cost' => 2500,
                'quantity' => 3,
                'price' => 3000,
                'currency' => 'IQD',
                'barcode' => '6920951560535',
                'is_active' => true,
                'image' => 'products/default_product.png',
            ],
            [
                'name' => 'اجنحة اطفال',
                'price_cost' => 4000,
                'quantity' => 3,
                'price' => 6500,
                'currency' => 'IQD',
                'barcode' => '6281234500106',
                'is_active' => true,
                'image' => 'products/default_product.png',
            ],
            [
                'name' => 'شمسيات هابي',
                'price_cost' => 5000,
                'quantity' => 8,
                'price' => 6000,
                'currency' => 'IQD',
                'barcode' => '6281234500137',
                'is_active' => true,
                'image' => 'products/default_product.png',
            ],
            [
                'name' => 'نشرة  ماشا',
                'price_cost' => 1500,
                'quantity' => 3,
                'price' => 2500,
                'currency' => 'IQD',
                'barcode' => '6281234500090',
                'is_active' => true,
                'image' => 'products/default_product.png',
            ],
            [
                'name' => 'نشرة هابي صغير',
                'price_cost' => 1500,
                'quantity' => 5,
                'price' => 3000,
                'currency' => 'IQD',
                'barcode' => '6281234500120',
                'is_active' => true,
                'image' => 'products/default_product.png',
            ],
            [
                'name' => 'بطاقات دعوة',
                'price_cost' => 1500,
                'quantity' => 16,
                'price' => 2500,
                'currency' => 'IQD',
                'barcode' => '6281234500083',
                'is_active' => true,
                'image' => 'products/default_product.png',
            ],
            [
                'name' => 'نشرة هابي كبير',
                'price_cost' => 4000,
                'quantity' => 4,
                'price' => 5000,
                'currency' => 'IQD',
                'barcode' => '6281234500144',
                'is_active' => true,
                'image' => 'products/default_product.png',
            ],
            [
                'name' => 'عوينات كرتون',
                'price_cost' => 1500,
                'quantity' => 7,
                'price' => 2500,
                'currency' => 'IQD',
                'barcode' => '6281234500113',
                'is_active' => true,
                'image' => 'products/default_product.png',
            ],
            [
                'name' => '1قاعدة كرتون (كيك)',
                'price_cost' => 7000,
                'quantity' => 2,
                'price' => 10000,
                'currency' => 'IQD',
                'barcode' => '8712417637534',
                'is_active' => true,
                'image' => 'products/default_product.png',
            ],
            [
                'name' => '2قاعدة كرتون (كيك)',
                'price_cost' => 5000,
                'quantity' => 2,
                'price' => 10000,
                'currency' => 'IQD',
                'barcode' => '8712417637503',
                'is_active' => true,
                'is_featured' => true,
                'is_best_selling' => false,
                'sales_count' => 15,
                'image' => 'products/default_product.png',
            ],
        ];

        foreach ($products as $productData) {
            Product::firstOrCreate(
                ['barcode' => $productData['barcode']],
                $productData
            );
        }

        $this->command->info('تم إنشاء المنتجات بنجاح!');
    }
}
